name: Tasks Verification

on:
  push:
  pull_request:

jobs:
  task1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 1
      run: python "task1.py"
    # Sauvegarde le flag1.txt généré par la task 1
    - name: Upload Flag 1
      uses: actions/upload-artifact@v4
      with:
        name: flag1-artifact
        path: flag1.txt

  task2:
    needs: task1
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # Récupère le flag1.txt pour que task2.py puisse le lire
    - name: Download Flag 1
      uses: actions/download-artifact@v4
      with:
        name: flag1-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 2
      run: python "task2.py"
    - name: Upload Flag 2
      uses: actions/upload-artifact@v4
      with:
        name: flag2-artifact
        path: flag2.txt

  task3:
    needs: task2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 2
      uses: actions/download-artifact@v4
      with:
        name: flag2-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 3
      run: python "task3.py"
    - name: Upload Flag 3
      uses: actions/upload-artifact@v4
      with:
        name: flag3-artifact
        path: flag3.txt

  task4:
    needs: task3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 3
      uses: actions/download-artifact@v4
      with:
        name: flag3-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 4
      run: python "task4.py"
    - name: Upload Flag 4
      uses: actions/upload-artifact@v4
      with:
        name: flag4-artifact
        path: flag4.txt

  task5:
    needs: task4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 4
      uses: actions/download-artifact@v4
      with:
        name: flag4-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 5
      run: python "task5.py"
    - name: Upload Flag 5
      uses: actions/upload-artifact@v4
      with:
        name: flag5-artifact
        path: flag5.txt

  task6:
    needs: task5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 5
      uses: actions/download-artifact@v4
      with:
        name: flag5-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 6
      run: python "task6.py"
    - name: Upload Flag 6
      uses: actions/upload-artifact@v4
      with:
        name: flag6-artifact
        path: flag6.txt

  task7:
    needs: task6
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 6
      uses: actions/download-artifact@v4
      with:
        name: flag6-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 7
      run: python "task7.py"
    - name: Upload Flag 7
      uses: actions/upload-artifact@v4
      with:
        name: flag7-artifact
        path: flag7.txt

  task8:
    needs: task7
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 7
      uses: actions/download-artifact@v4
      with:
        name: flag7-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 8
      run: python "task8.py"
    - name: Upload Flag 8
      uses: actions/upload-artifact@v4
      with:
        name: flag8-artifact
        path: flag8.txt

  task9:
    needs: task8
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 8
      uses: actions/download-artifact@v4
      with:
        name: flag8-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 9
      run: python "task9.py"
    - name: Upload Flag 9
      uses: actions/upload-artifact@v4
      with:
        name: flag9-artifact
        path: flag9.txt

  task10:
    needs: task9
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 9
      uses: actions/download-artifact@v4
      with:
        name: flag9-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 10
      run: python "task10.py"
    - name: Upload Flag 10
      uses: actions/upload-artifact@v4
      with:
        name: flag10-artifact
        path: flag10.txt

  task11:
    needs: task10
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 10
      uses: actions/download-artifact@v4
      with:
        name: flag10-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 11
      run: python "task11.py"
    - name: Upload Flag 11
      uses: actions/upload-artifact@v4
      with:
        name: flag11-artifact
        path: flag11.txt

  task12:
    needs: task11
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 11
      uses: actions/download-artifact@v4
      with:
        name: flag11-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 12
      run: python "task12.py"
    - name: Upload Flag 12
      uses: actions/upload-artifact@v4
      with:
        name: flag12-artifact
        path: flag12.txt

  task13:
    needs: task12
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 12
      uses: actions/download-artifact@v4
      with:
        name: flag12-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 13
      run: python "task13.py"
    - name: Upload Flag 13
      uses: actions/upload-artifact@v4
      with:
        name: flag13-artifact
        path: flag13.txt

  task14:
    needs: task13
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Download Flag 13
      uses: actions/download-artifact@v4
      with:
        name: flag13-artifact
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Task 14
      run: python "task14.py"